require("core.pluginConfig.gruvbox")
require("core.pluginConfig.lualine")
require("core.pluginConfig.nvim-tree")
require("core.pluginConfig.treesitter")
require("core.pluginConfig.lspConfig")
require("core.pluginConfig.completions")
