require("core.pluginConfig.everforest")
require("core.pluginConfig.lualine")
require("core.pluginConfig.nvim-tree")
require("core.pluginConfig.treesitter")
require("core.pluginConfig.lspConfig")
require("core.pluginConfig.completions")
require("core.pluginConfig.obsidian")
require("core.pluginConfig.undofile")
